api:
  build: .
  links:
    - rethinkdb
    - elasticsearch
  volumes:
    - "./src:/opt/app/src"
  ports:
    - "80:12345"
rethinkdb:
  image: rethinkdb
  volumes:
    - "../data:/data"
elasticsearch:
  image: elasticsearch
logstash:
  image: nukr/logstash
  links:
    - elasticsearch
    - rethinkdb
